### ISSUE TITLE
New release needed

### ISSUE THREAD

**Issue by alerque** [jneem/scribl#11]
The last tagged release 0.3.1 no longer builds on the current Rust stable toolchain. The Git HEAD version does. I assume something in this (or more likely some dependency) have been fixed to work on current Rust compilers, but the upshot is that the last tagged release isn't really a usable thing.

I suggest doing a release sooner rather than later to get working builds again.

**Comment by jneem** [comment]
Thanks for letting me know, I'll see what I can do. It isn't as simple as releasing the HEAD version, unfortunately, because HEAD depends on druid's master branch and crates.io releases can only depend on released crates...

**Comment by jneem** [comment]
Ok, this turned out not to be too hard -- it was an issue in rustfft that was fixed in a newer version, so I just ran `cargo update` and it seems to work. I've released 0.3.2.

I still think it's worth using HEAD, though, because it has several improvements that won't make it to a release until druid does a new release...

**Comment by alerque** [comment]
Thanks! For my own use I'll keep using HEAD, but I package this for Arch Linux and kind of like Crates.io stable packages are dependent on upstream having stable tags. It's at least nice to have one that builds for that reason.

**Comment by jneem** [comment]
Thanks for packaging it!

**Comment by alerque** [comment]
Umm...thanks for the release, but the Cargo lock file didn't get updated to match the toml config. It needs a `cargo update`. I can do this to get a package built but since it kills the `--locked` status the build won't be reproducible.

**Comment by jneem** [comment]
Ah, sorry, I forgot to re-run `cargo update` after bumping the version. Is it an issue with the package on crates.io (it seems to build fine to me) or just with the tagged version here? If it's just the tagged version here, I updated Cargo.lock and made a new tag.

**Comment by alerque** [comment]
I haven't tried the install via crates.io, only building from source based on the tags here (which is typically the only relevant workflow for distro packagers).

**Comment by jneem** [comment]
Ok, then hopefully the new tag will fix it.

**Comment by alerque** [comment]
It did, and the [AUR recipie](https://aur.archlinux.org/packages/scribl/) is up to date. Thanks for the quick fixes.

**Comment by jneem** [comment]
Ah, oops, I left in the 0.3.3 tag (which was a typo). I'll leave it there so as not to break the package, but it points to the same thing as the (new) 0.3.2 tag, and if you run it then it will report a version of 0.3.2.
