### ISSUE TITLE
"failed to recognize file format" from mplayer

### ISSUE THREAD

**Issue by makoConstruct** [jneem/scribl#14]
Playing around, I rendered a file. The file rendered. I then try to play it in mplayer

```
» mplayer scribl_play1.mp4 
[ffmpeg/demuxer] mov,mp4,m4a,3gp,3g2,mj2: Invalid mdhd time scale 0, defaulting to 1
[ffmpeg/demuxer] mov,mp4,m4a,3gp,3g2,mj2: invalid STSD entries 0
[ffmpeg/demuxer] mov,mp4,m4a,3gp,3g2,mj2: error reading header
[lavf] avformat_open_input() failed
[ffmpeg/demuxer] mov,mp4,m4a,3gp,3g2,mj2: Invalid mdhd time scale 0, defaulting to 1
[ffmpeg/demuxer] mov,mp4,m4a,3gp,3g2,mj2: invalid STSD entries 0
[ffmpeg/demuxer] mov,mp4,m4a,3gp,3g2,mj2: error reading header
[lavf] avformat_open_input() failed
Failed to recognize file format.
```

So I tried it in vlc. It displays a blank black video, while outputting
```
[h264 @ 0x7fdc3cc3ae80] hardware accelerator failed to decode picture
[h264 @ 0x7fdc3cc57bc0] hardware accelerator failed to decode picture
[h264 @ 0x7fdc3cca07c0] hardware accelerator failed to decode picture
[h264 @ 0x7fdc3ccbd440] hardware accelerator failed to decode picture
[h264 @ 0x7fdc3ccda040] hardware accelerator failed to decode picture
[h264 @ 0x7fdc3ccf6d00] hardware accelerator failed to decode picture
[h264 @ 0x7fdc3cc3ae80] hardware accelerator failed to decode picture
[h264 @ 0x7fdc3cc57bc0] hardware accelerator failed to decode picture
[h264 @ 0x7fdc3cca07c0] hardware accelerator failed to decode picture
[h264 @ 0x7fdc3ccbd440] hardware accelerator failed to decode picture
...
```
Video card is an old gtx 760. Driver: proprietary 460.39.

**Comment by jneem** [comment]
Hm, strange. Does `gstreamer` work? That's what `scribl` uses to encode... you can try it with
```
$ gst-launch-1.0 playbin uri=file:///path/to/scribl_play1.mp4
```
Also, would you mind sharing the `mp4` file and the scribl file you created it with? Then I can try to reproduce.

**Comment by makoConstruct** [comment]
Debian doesn't seem to have gst-launch in its repositories.

Here's the file http://makopool.com/scribl_play1.mp4

**Comment by jneem** [comment]
Hm, vlc works for me (although it does spit out a bunch of warnings). 

https://user-images.githubusercontent.com/1448113/173168133-cb2f5bfb-9e4b-4e00-91de-7f45f6341406.mp4

It's definitely a problem that mplayer doesn't like the videos, though. I'll see if I can figure out better gstreamer settings...

By the way, gst-launch-1.0 should be in the debian `gstreamer1.0-tools` package.

**Comment by jneem** [comment]
Does it help if you add some audio? It seems like there might be a bug in gstreamer, where if the audio track is empty then it produces a corrupt file.

If this is indeed the issue then I can push a workaround.

**Comment by jneem** [comment]
I think this should be fixed in latest master, but please let me know either way...

**Comment by makoConstruct** [comment]
> Does it help if you add some audio? It seems like there might be a bug in gstreamer, where if the audio track is empty then it produces a corrupt file.
> 
> If this is indeed the issue then I can push a workaround.

I can confirm that this was it, it works with sound (although my sound recording was garbled, my computer has never been very good at recording sound, so if that's another bug I'm not the one to report it)

**Comment by jneem** [comment]
Thanks for checking! In that case it should be fixed on master, even without audio.
