### ISSUE TITLE
Broken screenshot link in README

### ISSUE THREAD

**Issue by chris-morgan** [jneem/scribl#2]
README contains a reference to https://raw.githubusercontent.com/jneem/scribl/master/scribl/sample/screenshot.png, but you renamed the master branch to trunk, so it’s broken. https://raw.githubusercontent.com/jneem/scribl/trunk/scribl/sample/screenshot.png is correct.

I believe you should be able to refer to just scribl/sample/screenshot.png these days and GitHub will sort it out properly. This is better for other branches and for viewing outside GitHub, too.

**Comment by jneem** [comment]
Thanks for letting me know!
